language: node_js
node_js:
    - "6"

branches:
    only:
        - "master"

before_install:
    - rm -f ./web-ext-artifacts/*.zip

script:
    - npm run build

after_success:
    - npm run coveralls
